
package com.orion.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MinFuncImplService", targetNamespace = "http://ws.orion.com/", wsdlLocation = "http://localhost:3030/ws/MinFuncImpl?wsdl")
public class MinFuncImplService
    extends Service
{

    private final static URL MINFUNCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MINFUNCIMPLSERVICE_EXCEPTION;
    private final static QName MINFUNCIMPLSERVICE_QNAME = new QName("http://ws.orion.com/", "MinFuncImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3030/ws/MinFuncImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MINFUNCIMPLSERVICE_WSDL_LOCATION = url;
        MINFUNCIMPLSERVICE_EXCEPTION = e;
    }

    public MinFuncImplService() {
        super(__getWsdlLocation(), MINFUNCIMPLSERVICE_QNAME);
    }

    public MinFuncImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MINFUNCIMPLSERVICE_QNAME, features);
    }

    public MinFuncImplService(URL wsdlLocation) {
        super(wsdlLocation, MINFUNCIMPLSERVICE_QNAME);
    }

    public MinFuncImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MINFUNCIMPLSERVICE_QNAME, features);
    }

    public MinFuncImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MinFuncImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MinFunc
     */
    @WebEndpoint(name = "MinFuncImplPort")
    public MinFunc getMinFuncImplPort() {
        return super.getPort(new QName("http://ws.orion.com/", "MinFuncImplPort"), MinFunc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MinFunc
     */
    @WebEndpoint(name = "MinFuncImplPort")
    public MinFunc getMinFuncImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.orion.com/", "MinFuncImplPort"), MinFunc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MINFUNCIMPLSERVICE_EXCEPTION!= null) {
            throw MINFUNCIMPLSERVICE_EXCEPTION;
        }
        return MINFUNCIMPLSERVICE_WSDL_LOCATION;
    }

}
